-- Automatisch erzeugt aus src/config/pricing.ts – nicht von Hand bearbeiten.
-- Neu erzeugen: npm run db:seed-sql
insert into public.services (group_id, option_id, label, hint, preis, mtl, dreh, sort_order) values
  ('branche', 'gastro', 'Gastronomie', 'Restaurant, Bar, Café, Catering', null, null, false, 0),
  ('branche', 'musik', 'Festival & Musik', 'Open Air, Club, Konzert, Artist', null, null, false, 1),
  ('leistungen', 'video', 'Video', 'Aftermovie, Imagefilm, Reels', null, null, false, 0),
  ('leistungen', 'foto', 'Foto', 'Food, Location, Event, Artist', null, null, false, 1),
  ('leistungen', 'web', 'Web', 'Website, Speisekarte, Tickets', null, null, false, 2),
  ('leistungen', 'ki', 'KI-Automatisierung', 'Content-Pipelines, Voice, n8n', null, null, false, 3),
  ('videoUmfang', 'kompakt', 'Kompakt', 'Halber Drehtag · 1 Clip (60 s) + 3 Reels', 990, null, true, 0),
  ('videoUmfang', 'standard', 'Standard', '1 Drehtag · Film (2–3 Min.) + 6 Reels', 1890, null, true, 1),
  ('videoUmfang', 'premium', 'Premium', '2 Drehtage · Multi-Cam · Film + 12 Reels', 3690, null, true, 2),
  ('videoExtras', 'drohne', 'Drohnenaufnahmen', 'Luftbilder von Location oder Crowd', 290, null, true, 0),
  ('videoExtras', 'zweitkamera', 'Zweite Kamera + Operator', 'Mehr Perspektiven, sichere Momente', 390, null, true, 1),
  ('videoExtras', 'gimbal', 'FPV- & Gimbal-Fahrten', 'Dynamische Kamerafahrten durch die Location', 240, null, true, 2),
  ('videoExtras', 'grading', 'Kino-Color-Grading', 'Eigener Look statt Standard-LUT', 190, null, false, 3),
  ('fotoUmfang', 'kompakt', 'Kompakt', '2 Stunden · 25 bearbeitete Fotos', 390, null, true, 0),
  ('fotoUmfang', 'standard', 'Standard', 'Halber Tag · 60 bearbeitete Fotos', 790, null, true, 1),
  ('fotoUmfang', 'premium', 'Premium', 'Ganzer Tag · 150 Fotos inkl. Retusche', 1490, null, true, 2),
  ('fotoExtras', 'styling', 'Food-Styling', 'Teller, Props und Licht wie im Magazin', 190, null, true, 0),
  ('fotoExtras', 'retusche', 'High-End-Retusche', 'Für Karte, Plakate und Großformate', 290, null, false, 1),
  ('fotoExtras', 'kivarianten', 'KI-Bildvarianten', 'Hintergründe, Formate, Saison-Versionen', 240, null, false, 2),
  ('webArt', 'speisekarte', 'Digitale Speisekarte', 'Mobile Karte mit QR-Code, jederzeit änderbar', 199, null, false, 0),
  ('webArt', 'onepager', 'One-Pager Website', 'Karte oder Line-up, Öffnungszeiten, Anfahrt', 399, null, false, 1),
  ('webArt', 'reservierung', 'Website mit Reservierung', 'Mehrseitig · Reservierung/Tickets rund um die Uhr', 699, null, false, 2),
  ('webArt', 'komplett', 'Website mit Bestellung', 'Reservierung + Online-Bestellung + Dashboard', 999, null, false, 3),
  ('webExtras', 'mehrsprachig', 'Zweite Sprache', 'z. B. Englisch oder Arabisch', 190, null, false, 0),
  ('webExtras', 'gmb', 'Google-Unternehmensprofil', 'Einrichtung und Optimierung mit Fotos & Karte', 149, null, false, 1),
  ('webExtras', 'seo', 'SEO-Startpaket', '„Restaurant in der Nähe“ – lokal gefunden werden', 290, null, false, 2),
  ('webExtras', 'geo', 'GEO für KI-Suchen', 'Sichtbar in ChatGPT, Gemini & Google AI', 290, null, false, 3),
  ('kiWorkflows', 'captions', 'Captions & Posting-Plan', 'Texte in deinem Ton, von uns redigiert', 490, null, false, 0),
  ('kiWorkflows', 'voiceover', 'KI-Voiceover & Übersetzung', 'Deine Clips in DE · EN · AR · TR', 590, null, false, 1),
  ('kiWorkflows', 'varianten', 'Ad-Varianten-Generator', 'Hooks, Längen, Formate für A/B-Tests', 890, null, false, 2),
  ('kiWorkflows', 'bewertungen', 'Bewertungs-Antworten', 'Google-Reviews automatisch beantworten', 490, null, false, 3),
  ('kiWorkflows', 'leads', 'Anfragen-Automatik', 'Reservierungen & Anfragen sortieren, weiterleiten', 690, null, false, 4),
  ('kiWorkflows', 'reporting', 'Reporting-Dashboard', 'Zahlen aus allen Kanälen, einmal pro Woche', 790, null, false, 5),
  ('anfahrt', 'lokal', 'Lokal', 'bis 50 km – inklusive', 0, null, false, 0),
  ('anfahrt', 'regional', 'Regional', 'bis 200 km', 90, null, false, 1),
  ('anfahrt', 'bundesweit', 'Deutschlandweit', 'inkl. Übernachtung', 290, null, false, 2),
  ('contentAbo', 'keins', 'Kein Abo', 'Einmaliges Projekt', null, 0, false, 0),
  ('contentAbo', 'basis', 'Social Basis', '6 Reels + 10 Fotos pro Monat', null, 790, false, 1),
  ('contentAbo', 'retainer', 'Social-Retainer', '12 Reels + 20 Fotos, Planung & Posting', null, 1490, false, 2),
  ('hosting', 'eigen', 'Bleibt bei meinem Anbieter', null, null, 0, false, 0),
  ('hosting', 'wartung', 'Hosting & Wartung', 'Domain, SSL, Backups, kleine Änderungen', null, 19, false, 1),
  ('kiBetrieb', 'keiner', 'Ohne Betreuung', 'Du betreibst die Workflows selbst', null, 0, false, 0),
  ('kiBetrieb', 'basis', 'Betrieb Basis', 'Monitoring, Updates, Fehlerbehebung', null, 49, false, 1),
  ('kiBetrieb', 'aktiv', 'Betrieb Aktiv', 'Zusätzlich Weiterentwicklung jeden Monat', null, 129, false, 2)
on conflict (group_id, option_id) do update set
  label = excluded.label, hint = excluded.hint, preis = excluded.preis,
  mtl = excluded.mtl, dreh = excluded.dreh, sort_order = excluded.sort_order;
