-- Automatisch erzeugt aus src/config/pricing.ts – nicht von Hand bearbeiten.
-- Neu erzeugen: npm run db:seed-sql
insert into services (group_id, option_id, label, hint, preis, mtl, dreh, sort_order) values
  ('branche', 'gastro', 'Gastronomie & Food', 'Restaurant, Lieferdienst, Bäckerei, Café', null, null, false, 0),
  ('branche', 'immobilien', 'Immobilien & Verwaltung', 'Makler, Hausverwaltung, Bauträger', null, null, false, 1),
  ('branche', 'automotive', 'Automotive & Mobilität', 'Autohaus, Werkstatt, Fahrschule, Vermietung', null, null, false, 2),
  ('branche', 'kanzlei', 'Kanzleien & Beratung', 'Steuerberater, Anwälte, Makler, Coaches', null, null, false, 3),
  ('branche', 'beauty', 'Beauty, Gesundheit & Wellness', 'Friseur, Barber, Kosmetik, Physio, Studio', null, null, false, 4),
  ('branche', 'handwerk', 'Handwerk & Dienstleistungen', 'Handwerk, Reinigung, Umzug, Services', null, null, false, 5),
  ('branche', 'musik', 'Events, Festivals & Artists', 'Veranstalter, Clubs, Labels, Artists', null, null, false, 6),
  ('branche', 'andere', 'Andere Branche', 'Handel, Bildung, Vereine, Verbände', null, null, false, 7),
  ('leistungen', 'bestellung', 'Bestellsystem', 'Online-Bestellung ohne Provision', null, null, false, 0),
  ('leistungen', 'buchung', 'Buchungssystem', 'Termine, Reservierungen, Kurse', null, null, false, 1),
  ('leistungen', 'website', 'Website', 'Neu oder Relaunch, SEO & KI-Suche', null, null, false, 2),
  ('leistungen', 'portal', 'Web-App & Kundenportal', 'Login, Dokumente, Status, Self-Service', null, null, false, 3),
  ('leistungen', 'dashboard', 'Dashboard & Reporting', 'Alle Zahlen an einem Ort', null, null, false, 4),
  ('leistungen', 'software', 'Individuelle Software', 'Deine Prozesse als eigenes System', null, null, false, 5),
  ('leistungen', 'app', 'Mobile App', 'iOS & Android', null, null, false, 6),
  ('leistungen', 'ki', 'KI-Automatisierung', 'Workflows, Agenten, Dokumente', null, null, false, 7),
  ('leistungen', 'media', 'Premium-Media', 'Event-, Artist- oder Brand-Film', null, null, false, 8),
  ('websiteUmfang', 'onepager', 'One-Pager', 'Eine starke Seite mit Kontakt, Karte & WhatsApp', 1190, null, false, 0),
  ('websiteUmfang', 'business', 'Business-Website', 'Bis 8 Seiten · CMS · Anfrage-Funnel · SEO-Basis', 1990, null, false, 1),
  ('websiteUmfang', 'pro', 'Website Pro', 'Mehrsprachig · Blog · Landingpages · Tracking', 3490, null, false, 2),
  ('websiteExtras', 'seo', 'Lokales SEO-Paket', 'Gefunden werden bei „… in der Nähe“', 490, null, false, 0),
  ('websiteExtras', 'geo', 'GEO für KI-Suchen', 'Sichtbar in ChatGPT, Gemini & Google AI', 390, null, false, 1),
  ('websiteExtras', 'gmb', 'Google-Unternehmensprofil', 'Einrichtung und Optimierung', 190, null, false, 2),
  ('websiteExtras', 'texte', 'Texte & Bildaufbereitung', 'Wir schreiben, du gibst frei', 490, null, false, 3),
  ('bestellUmfang', 'start', 'Bestellsystem Start', 'Speisekarte · Warenkorb · Abholung & Lieferung · Bestell-Dashboard', 2900, null, false, 0),
  ('bestellUmfang', 'pro', 'Bestellsystem Pro', '+ Online-Zahlung · Küchen-Display · Liefergebiete · Gutscheine', 4900, null, false, 1),
  ('bestellUmfang', 'filialen', 'Mehrere Standorte', 'Filialen · Rollen · zentrales Reporting', 7900, null, false, 2),
  ('buchungUmfang', 'start', 'Buchung Start', 'Leistungen · Kalender · Bestätigung per Mail & WhatsApp', 2200, null, false, 0),
  ('buchungUmfang', 'pro', 'Buchung Pro', '+ Kundenkonto · Anzahlung · Erinnerungen · Warteliste', 3900, null, false, 1),
  ('buchungUmfang', 'team', 'Team & Standorte', 'Mehrere Mitarbeiter, Räume oder Filialen · Schichtplan', 6400, null, false, 2),
  ('portalUmfang', 'basis', 'Kundenportal', 'Login · Dokumente · Status · Nachrichten', 7400, null, false, 0),
  ('portalUmfang', 'erweitert', 'Portal mit Workflows', '+ Rollen · Formulare · Freigaben · Automationen', 12900, null, false, 1),
  ('dashboardUmfang', 'basis', 'Dashboard', 'Kennzahlen aus 2–3 Quellen, täglich aktuell', 4900, null, false, 0),
  ('dashboardUmfang', 'pro', 'Dashboard Pro', 'Echtzeit · Rollen · Alarme · Prognosen', 8900, null, false, 1),
  ('softwareUmfang', 's', 'Ein Kernprozess', 'z. B. Auftrag → Einsatz → Rechnung als eigenes System', 10900, null, false, 0),
  ('softwareUmfang', 'm', 'Mehrere Prozesse', 'Rollen & Rechte · Schnittstellen · Admin-Bereich', 18900, null, false, 1),
  ('softwareUmfang', 'l', 'Plattform', 'Mehrere Abteilungen oder Standorte, individuelle Module', 29900, null, false, 2),
  ('appUmfang', 'pwa', 'Web-App für den Homescreen', 'iOS & Android ohne App Store · Push', 3900, null, false, 0),
  ('appUmfang', 'native', 'Native App', 'App Store & Google Play · Offline · Push', 9900, null, false, 1),
  ('funktionen', 'zahlung', 'Online-Zahlung', 'Stripe, PayPal, Apple Pay, Google Pay', 890, null, false, 0),
  ('funktionen', 'schnittstellen', 'Schnittstellen', 'Kasse, DATEV, CRM, ERP oder Warenwirtschaft', 1490, null, false, 1),
  ('funktionen', 'ki', 'KI-Funktion', 'Chat, Dokumente auslesen, Texte vorschlagen', 1490, null, false, 2),
  ('funktionen', 'whatsapp', 'WhatsApp-Benachrichtigungen', 'Bestätigungen und Status automatisch', 590, null, false, 3),
  ('funktionen', 'mehrsprachig', 'Mehrsprachig', 'z. B. Deutsch, Englisch, Arabisch, Türkisch', 690, null, false, 4),
  ('funktionen', 'migration', 'Datenübernahme', 'Aus Excel, Papierlisten oder dem Altsystem', 990, null, false, 5),
  ('kiWorkflows', 'anfragen', 'Anfragen-Automatik', 'Mails & Formulare sortieren, beantworten, weiterleiten', 990, null, false, 0),
  ('kiWorkflows', 'dokumente', 'Dokumente & Belege', 'Automatisch auslesen, ablegen, prüfen', 1290, null, false, 1),
  ('kiWorkflows', 'telefon', 'KI-Telefonassistent', 'Nimmt Anrufe an, bucht Termine, fasst zusammen', 1490, null, false, 2),
  ('kiWorkflows', 'chatbot', 'Website-Chat', 'Beantwortet Fragen mit deinem Wissen, rund um die Uhr', 1190, null, false, 3),
  ('kiWorkflows', 'bewertungen', 'Bewertungs-Antworten', 'Google-Reviews im Ton des Hauses', 590, null, false, 4),
  ('kiWorkflows', 'reporting', 'Wochen-Report', 'Zahlen aus allen Tools, einmal pro Woche', 890, null, false, 5),
  ('mediaPaket', 'brand', 'Brand- & Hospitality-Film', '1 Drehtag · Imagefilm + 6 Reels · Kino-Grading', 2990, null, true, 0),
  ('mediaPaket', 'artist', 'Artist-Kampagne', 'Musikvideo oder Visualizer · Press-Kit · 8 Reels', 3490, null, true, 1),
  ('mediaPaket', 'festival', 'Festival & Event Premium', 'Multi-Cam-Crew · Aftermovie in 7 Tagen · 20+ Ad-Varianten', 4900, null, true, 2),
  ('mediaExtras', 'drohne', 'Drohnenaufnahmen', 'Luftbilder von Location oder Crowd', 290, null, true, 0),
  ('mediaExtras', 'zweitkamera', 'Zweite Kamera + Operator', 'Mehr Perspektiven, sichere Momente', 390, null, true, 1),
  ('mediaExtras', 'varianten', 'KI-Sprachfassungen', 'Voiceover & Untertitel in DE · EN · AR · TR', 490, null, false, 2),
  ('anfahrt', 'lokal', 'Lokal', 'bis 50 km – inklusive', 0, null, false, 0),
  ('anfahrt', 'regional', 'Regional', 'bis 200 km', 90, null, false, 1),
  ('anfahrt', 'bundesweit', 'Deutschlandweit', 'inkl. Übernachtung', 290, null, false, 2),
  ('betrieb', 'selbst', 'Selbst betreiben', 'Du bekommst Code & Zugänge, Hosting übernimmst du', null, 0, false, 0),
  ('betrieb', 'wartung', 'Hosting & Wartung', 'Server, SSL, Backups, Sicherheitsupdates', null, 49, false, 1),
  ('betrieb', 'betrieb', 'Betrieb & Support', '+ Monitoring, Support, kleine Änderungen', null, 149, false, 2),
  ('betrieb', 'wachstum', 'Weiterentwicklung', '+ jeden Monat neue Funktionen (ca. 1 Tag)', null, 490, false, 3)
on conflict (group_id, option_id) do update set
  label = excluded.label, hint = excluded.hint, preis = excluded.preis,
  mtl = excluded.mtl, dreh = excluded.dreh, sort_order = excluded.sort_order;
