/**
 * Galerie: Flyer & Flyer-Animationen aus echten Event-Reihen (Clubs, Partys, Festivals).
 * Assets liegen optimiert unter public/portfolio/{flyers,motion} (WebP 720 px, MP4-Loops 540×960, ohne Ton).
 * Eigennamen (Reihen, Events) werden nicht übersetzt; Sektionstexte: messages/{de,en}.json → portfolio.gallery.
 * Neue Arbeiten: Datei ablegen, hier eintragen – Slider, Filter und Lightbox ziehen automatisch nach.
 */

export type GallerySeries = "vibe" | "hnb" | "ayr" | "firstclass" | "jade" | "money" | "nonstop" | "allin" | "wuwh" | "blessed" | "candy" | "berlin" | "savage" | "luvsick" | "yves" | "catchme";

/** Anzeigenamen der Reihen (Filter-Chips) – in der Reihenfolge, in der sie erscheinen */
export const gallerySeries: { id: GallerySeries; name: string }[] = [
  { id: "vibe", name: "Vibe Club" },
  { id: "hnb", name: "Hot'n Brownie" },
  { id: "ayr", name: "AYR" },
  { id: "firstclass", name: "First Class" },
  { id: "jade", name: "Jade" },
  { id: "money", name: "Money Talkz" },
  { id: "nonstop", name: "Nonstop" },
  { id: "allin", name: "All In" },
  { id: "wuwh", name: "WUWH" },
  { id: "blessed", name: "Blessed" },
  { id: "candy", name: "Candy Night" },
  { id: "berlin", name: "Berlin" },
  { id: "savage", name: "4Ever Savage" },
  { id: "luvsick", name: "LUVSICK" },
  { id: "yves", name: "YVES Club" },
  { id: "catchme", name: "Catch Me" },
];

export interface GalleryFlyer {
  id: string;
  series: GallerySeries;
  title: string;
  src: string;
  width: number;
  height: number;
  blur: string;
}

export interface GalleryMotion {
  id: string;
  series: GallerySeries;
  title: string;
  video: string;
  poster: string;
  blur: string;
}

export const galleryFlyers: GalleryFlyer[] = [
  { id: "allin-flyer", series: "allin", title: "All In · Live Night", src: "/portfolio/flyers/allin-flyer.webp", width: 720, height: 1280, blur: "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAADQAwCdASoMABUAPu1iqU2ppaOiMAgBMB2JQAB8jUX58Wo5Opej/UAA/uwQ45UMbr/G4rT97WMt5u/Z+x/NregGAkXnLSPZ9VAjeuCHxsNRgR+Y3eWAf2oki27nzsuft5ji9pgeVbbtBpOWN9i0qxOIz7kIgAAA" },
  { id: "ayr-flyer", series: "ayr", title: "AYR · Are You Ready?", src: "/portfolio/flyers/ayr-flyer.webp", width: 720, height: 1280, blur: "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAABwBACdASoMABUAPu1iqU2ppaOiMAgBMB2JaACdMoAlsxgrFbEbNqkQXW1ZVAD+7t0Wizz2WDuUWKvxLqsglKcm6DENwzHoxei4AZnfNfqlX2BqBSSK9+N6i7aDvtGSl5cjGsZy0wlqrCZcmcqx9jl4lMQ+x7DlpZuodmtmVAgvCuCoAN5y5U8dkcoXWqO846UdZrgA" },
  { id: "ayr-teaser", series: "ayr", title: "AYR · Teaser", src: "/portfolio/flyers/ayr-teaser.webp", width: 720, height: 1280, blur: "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAADwAwCdASoMABUAPu1iqU2ppaOiMAgBMB2JbACdMoACpf5BlBSyokIQAP7sTWRYlmkooQPoZDUa1MiTgKf0wkcC3B/ZIPvYUwcB0/CWkiyk6ng7Cpx4jEx+OBga0Z7y64SAUyl/VP1jW+SKjGqaL51W94gLunrPuKPwkWE4c3x35zzCCPelrB3EBJyamD0BJqQwK/bhgTBWqTFAAAA=" },
  { id: "ayr-geek", series: "ayr", title: "AYR · Geek Live", src: "/portfolio/flyers/ayr-geek.webp", width: 720, height: 1280, blur: "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAADQAwCdASoMABUAPu1iqU2ppaQiMAgBMB2JZAC/OBuZz3ETLTVdRwAA/uv74nm1s/0Eaxn/5IuyUSb+uo7xP9f5/5S9hEBP7CewfblL5HYDKda+SK13tgDDJQbi4eYHYAA=" },
  { id: "firstclass-haupt", series: "firstclass", title: "First Class · Cabin Crew Special", src: "/portfolio/flyers/firstclass-haupt.webp", width: 720, height: 1280, blur: "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAADwAwCdASoMABUAPu1iqU2ppaOiMAgBMB2JYgCdMoAC+nYqxUr/ZyCgAP7HaSe7Gsz1UrSTjzXAO7xkKb/2YJu2WOVFzzTjmuMe+Po30BSyzKnBiShhEFKXqL/LbuZ/fHgfH7c/rQGHXnKWPpd478Q/yh9YAAAA" },
  { id: "firstclass-crew", series: "firstclass", title: "First Class · Cabin Crews", src: "/portfolio/flyers/firstclass-crew.webp", width: 720, height: 1280, blur: "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAADQAwCdASoMABUAPu1iqU2ppaOiMAgBMB2JZQCw7Bt1vytd03KJUIAA/oWpxShFYFhNCCN6XvNKEVabE8lBONLlaPGlnEObiWGi/eFq1Js/zOmXAk6ZQv2QAFL6hNyET9jV/cNkzjrOtxuMKMVbX0ZGioTkyEq+lljxXwAA" },
  { id: "hnb-flyer", series: "hnb", title: "Hot'n Brownie · Belle Club", src: "/portfolio/flyers/hnb-flyer.webp", width: 720, height: 1280, blur: "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAACwBACdASoMABUAPu1iqU2ppaOiMAgBMB2JaACdMoMlwcAAwiQJLwowMQWUeYgAAP7vZ3eJa+1Be3wPT2Nu23HuXg9szLinPS+jiHjMF7HE6pmK0vwUqVsLA4Sb8jXqn6GEeXJmtmDAhupmoq5MnIcOxq617cBjIYMIh4wx/6pzUzPLqAA=" },
  { id: "hnb-2007", series: "hnb", title: "Hot'n Brownie · 20.07", src: "/portfolio/flyers/hnb-2007.webp", width: 720, height: 1280, blur: "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAAAwBACdASoMABUAPu1iqU2ppaOiMAgBMB2JbACdMoR4GCKYishd5/rJtAAA/qWAbtCcj00E4MUz/folqJli6SwmYs2KvH79ULAy2vLKTRTH/8yQ6BP7okFlanKUgYlI29Z7/m1Mc8dfElvyL7gD8Cw1ZqRGti7P2ZG/10x8lq+L/zMlGfJ+D0QO68UpLf78Oj1U1jyriG0pvnR5L+AAAA==" },
  { id: "hnb-liar-teaser", series: "hnb", title: "Hot'n Brownie · Teaser", src: "/portfolio/flyers/hnb-liar-teaser.webp", width: 720, height: 1280, blur: "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAABwBACdASoMABUAPu1iqU2ppaOiMAgBMB2JbACdMoR3IsAAs44p4IcDILDXoAD+pVGPbr9pcAHpQToWNjMPBFtph+Mg2/Vu/reWrIacnepcjo+Fv+JPn//fgD345Yyg1175aC4ejiLPptl+evZWunqK/g6P1qljK/zB1r/g7yPsnKObR9eoiu8I2hOxPJz3X0BBFcgAAAA=" },
  { id: "jade-ggg-planet", series: "jade", title: "Jade · Girls Girls Girls", src: "/portfolio/flyers/jade-ggg-planet.webp", width: 720, height: 1280, blur: "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAADQAwCdASoMABUAPu1iqU2ppaOiMAgBMB2JaACdAYs2sqb+fx7/u7AA/mo6puqZlLzWVJfyryWMHrpq+QwhUTNYjEbmCQxbH1kR//RQc2KwnsBb+jHVL3YYv6JMCBareYaS/hx17/42+4Wq8ZtDyGLZ1uX2FCUKGY+EfVenAcDxq0WVu6JpD9esmu4AAA==" },
  { id: "money-neby", series: "money", title: "Money Talkz · Friday", src: "/portfolio/flyers/money-neby.webp", width: 720, height: 1280, blur: "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAADQAwCdASoMABUAPu1iqU2ppaOiMAgBMB2JZQAAW78sOv6gP+X/40AA/u8oSPK6LPx6vvU6waa7HNPiggwIS1R1X4oTM3eDAwS8tLNuQ6ZmV6vvvb7zvdi50q9Pxn5A8MCeNjO9IUXvM7tyMzUSPwhMgAA=" },
  { id: "money-sept", series: "money", title: "Money Talkz · Sept Night", src: "/portfolio/flyers/money-sept.webp", width: 720, height: 1280, blur: "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAABQBACdASoMABUAPu1iqU2ppaOiMAgBMB2JZwDImywBhezNIeq3Cw+hO4mAAP7s5xDGtgyJf72tJGjEuTo2ZeJsRUyVzA5Ei4h9nwegJpGAieyZT4FPtuC9US6+zVG7xEoGu8kqiqvyLCoFUZcf5UamSwFEuqIcjo3ove89VGB/AAAA" },
  { id: "nonstop-teaser", series: "nonstop", title: "Nonstop Events · Vanity", src: "/portfolio/flyers/nonstop-teaser.webp", width: 720, height: 1280, blur: "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAABwAwCdASoMABUAPu1iqU2ppaOiMAgBMB2JZQAAXlvBz0pNbAAA/vKlTHy9NYlNNuhb5tsSKD+Ibv2WkIa/DA2ICUy1uNuYhtxbycqyRm8gAToX6Lce9dmDIs282NeQgAA=" },
  { id: "nonstop-1705", series: "nonstop", title: "Nonstop Events · 17.05", src: "/portfolio/flyers/nonstop-1705.webp", width: 720, height: 1280, blur: "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAABQAwCdASoMABUAPu1iqU2ppaOiMAgBMB2JYwAAXlvNyytaQAD+8qVMf8ZMeTMPmNdkdxgaCgc4imKkt7IcuQfVwTYA8jmYQYhvnxa/d3Jwx8YzkC+ZlbGHkk4h5gUzUHWAAA==" },
  { id: "vibe-flyer", series: "vibe", title: "Vibe · Reopening", src: "/portfolio/flyers/vibe-flyer.webp", width: 720, height: 1280, blur: "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAABQBACdASoMABUAPu1iqU2ppaOiMAgBMB2JYgCdAYu43FHhLyP6+Vkb8hagAP6FE/ReStpRmNwP/Pcefux3xIg3hEjP8GyENX1eaM/h0ustOXlARxPPe8HfWhzgkglsET3P2o10pJ//uOIjh9CCNnW49O1b0eT2PYU3IKzv3GboILYL4CKaS1XIDXywHtwAAAA=" },
  { id: "vibe-reopening", series: "vibe", title: "Vibe · Reopening Festival", src: "/portfolio/flyers/vibe-reopening.webp", width: 720, height: 1280, blur: "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAAAQBACdASoMABUAPu1iqU2ppaOiMAgBMB2JbACdMoADReEQ6HWSR3mzwAD+CO5l6pm2YBZ64NUUGKhEpyDNF78FggTIaV6WksXujva4Quir5rtOZaSRiFOBwg7LFGGEAoEFEUcN08/3xgZvt2fpQA49dn+vYpU3zPoX/2Pr71Sqks3HLUUwHm1+shwskqCNRWxzKx4rM9qx+KAA" },
  { id: "vibe-russki", series: "vibe", title: "Vibe · Russki Rave", src: "/portfolio/flyers/vibe-russki.webp", width: 720, height: 1280, blur: "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAAAwBACdASoMABUAPu1iqU2ppaOiMAgBMB2JZAC7LwAB0bfrT0GvoWbd7IAA/tb0hVASRRjtIHBBkgIlhl7PY1se4+I0MAioRyovcsMbjAcLJLdWWGKsfswIAj+TchGnzboaeuHWl3kq17j0eTc6XWi0eIFSsXyJusXgAA==" },
  { id: "wuwh-dawn", series: "wuwh", title: "WUWH · The Dawn", src: "/portfolio/flyers/wuwh-dawn.webp", width: 720, height: 1280, blur: "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAADQAwCdASoMABUAPu1iqU2ppaQiMAgBMB2JYwCo9CB+JJefj+5UgGAA/rO1iStnbflPlzg4gf6q9XL0zg4eFzHmffvHkqMLayzXjINRDPhe6cDPPnXuMLwAiZ54QPTDoZo53pm/xlURhgAA" },
  { id: "berlin-elex", series: "berlin", title: "Berlin · Elex 4 Friends", src: "/portfolio/flyers/berlin-elex.webp", width: 720, height: 1280, blur: "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAADwAwCdASoMABUAPu1iqU2ppaOiMAgBMB2JZwAAW+NKBg4EDhGC1PiEAP7S5rCi3rf1XCyqFOWOH6p4MH1w8RobIrM8vE+odrSu3rq84x77i5ZE3fIAgvRjLfVmKhd8jdkcfx6DC+En9iTPCJk/yha00xrh2dAAAAA=" },
  { id: "savage-4es", series: "savage", title: "4Ever Savage · Bad Chicks", src: "/portfolio/flyers/savage-4es.webp", width: 720, height: 1280, blur: "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAADQAwCdASoMABUAPu1iqU2ppaOiMAgBMB2JQBOgA8+bJ4+4p03kj1AA/u9iJ1H7DdN+S9YESRKlkpobedwiHVWWGgbOlHPsh0OrOe2RU2k94/F4+/hOfyh12G7P1WMdzhiUYr/ngeiH475aakLSDOQt9veddmYhU6r3m5dFxEAZpN+4AAA=" },
  { id: "blessed-albanien", series: "blessed", title: "Blessed · Albanien Night", src: "/portfolio/flyers/blessed-albanien.webp", width: 720, height: 1280, blur: "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAADwAwCdASoMABUAPu1iqU2ppaOiMAgBMB2JZAC7ACB+FhaxDFEcCTBwAP7usaiuyA548QeSiK/5R87iLhMwhyulrFiO5Xl8pLOXPPw+N490xFYZ/h8DiWwBrxlXrBU+AVht4RXnkRQihVBqmOk9oZUJQ8U9XrYrWEAc92TIAAA=" },
  { id: "blessed-friday", series: "blessed", title: "Blessed · Friday", src: "/portfolio/flyers/blessed-friday.webp", width: 720, height: 1280, blur: "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAAAwBACdASoMABUAPu1iqU2ppaOiMAgBMB2JbACdMoMYAEQZ7T8mpn8YVNAA/n6iI3W+JcUOYPrsAedKVyiUdNwnRvP5Rdu+pIlrcvTZBnm5/evlUTnZ3ZlUWuh0zI/WQrT9B1/5LeujlMzYFuXYytymncEWYAAA" },
  { id: "blessed-saturday", series: "blessed", title: "Blessed · Saturday", src: "/portfolio/flyers/blessed-saturday.webp", width: 720, height: 1280, blur: "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAABwBACdASoMABUAPu1iqU2ppaOiMAgBMB2JaACdMoR3Ff/gPfCwzeBCPNH8aAD+LMHaQNPPEnhQ/0b5lT7+t27coFp5MJ/vw/d91g/fAFk8DGF590c8SwNr45u+ZrxtWqEBZqtvlTrFjmDlyk7PAAAA" },
  { id: "candy-monalisa", series: "candy", title: "Candy Night · Monalisa", src: "/portfolio/flyers/candy-monalisa.webp", width: 720, height: 1280, blur: "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAADQAwCdASoMABUAPu1iqU2ppaOiMAgBMB2JagAAShf0p22SKd/jQMAA93jq/xSy+S9zLmVZljfPFtlaqgOu/fZOgjbLuKhr+rSe+DAg8pALouQr/orKjfR9yAH7336qLSUooo7rq6euBeAw6AsSpivoKYWUW6UAAAA=" },
  { id: "luvsick-five-years", series: "luvsick", title: "LUVSICK · Five Years", src: "/portfolio/flyers/luvsick-five-years.webp", width: 720, height: 1280, blur: "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAADQAwCdASoMABUAPu1iqU2ppaOiMAgBMB2JbAAAXkPsZEzw9tKWyAAA/oSljiSxy8v+DUWrngR7B0c/cYRl61Wsr/TF11DlbUENfbLVg8kJgvegfBCUpW4537c/uVpsj3rZsh/g60P5WcXVHC+Z1A/hu26ukrYAAAA=" },
  { id: "luvsick-five-years-b", series: "luvsick", title: "LUVSICK · Five Years (Look 2)", src: "/portfolio/flyers/luvsick-five-years-b.webp", width: 720, height: 1280, blur: "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAADQAwCdASoMABUAPu1iqU2ppaOiMAgBMB2JYgAAXdLB+2GcfbQ6LPAA/oSljiSxy8v+DUkmN0oOelEjQVgnWdMg3p5ZlmTNixoolhxwEzyo0dbu9WYPnIjPQjt6bOcId5Blj3b56Jt7AUN1AgjD/4kAAAA=" },
];

export const galleryMotion: GalleryMotion[] = [
  { id: "hnb", series: "hnb", title: "Hot'n Brownie", video: "/portfolio/motion/hnb.mp4", poster: "/portfolio/motion/hnb.webp", blur: "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAACwAwCdASoMABUAPu1kqU2ppaOiMAgBMB2JYwCdACFsBj3LcA2FgAD+72F3irpgi55P7MpGeELWzqj9bTeZJzW+JdRQ17A2ueHmSkTZitHkAA==" },
  { id: "hnb2007", series: "hnb", title: "Hot'n Brownie · 20.07", video: "/portfolio/motion/hnb2007.mp4", poster: "/portfolio/motion/hnb2007.webp", blur: "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAABQBACdASoMABUAPu1iqU2ppaOiMAgBMB2JagCdMoRwN5WAPCoJ+KSMDBQAAPcDBw/ZB+JIeFp9P5LD69JrUo3uMCIj5NqCJHis2Hg8HyOHxwgmt8jmUT/PJ+lB+F9Gh88r27hTSv2FGeGAAAA=" },
  { id: "ayr", series: "ayr", title: "AYR · Are You Ready?", video: "/portfolio/motion/ayr.mp4", poster: "/portfolio/motion/ayr.webp", blur: "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAABwBACdASoMABUAPu1iqU2ppaOiMAgBMB2JbACdAYtK33V48VTexKHnVgRcQAD+6aOpkmvKxVANQu4SmODTfZqTColl5PX/12VfvveET6NnqypWSZinfmRlQ4K58OQhNH2R3T1rmimvE+dRKtFhmVGIf53tP/BR3vfwF0Cbfe1b4v/JZTcbkiLW1/1g+YyW2sPAaxbzRBmbPLOetErgAA==" },
  { id: "noizy", series: "ayr", title: "AYR · Noizy", video: "/portfolio/motion/noizy.mp4", poster: "/portfolio/motion/noizy.webp", blur: "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAACwAwCdASoMABUAPu1iqU2ppaQiMAgBMB2JQBOgAdx9vtocxpxz8AD+2Bo8lHrL5bNzJNWDnXlJGpHFiy1AWkMTW8fng5X35ETDi5ax3Maom33nIc7O4QFqRw30AMhBrZoqerU3J1BwQkgA" },
  { id: "russki", series: "vibe", title: "Vibe · Russki Rave", video: "/portfolio/motion/russki.mp4", poster: "/portfolio/motion/russki.webp", blur: "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAQBACdASoMABUAPu1iqU2ppaOiMAgBMB2JYgC7Ef/gMP1NWiDzwHPgMAD8z9RBOpvfcdFyeH7UinGPBH8bskm+0bacdH+IwHO0XeeWj1l0+CbZB+FnIFEZ2ZmLT/ny99tmf1epwZonuNDN5XTpCAAA" },
  { id: "wuwh", series: "wuwh", title: "WUWH · The Dawn (3D)", video: "/portfolio/motion/wuwh.mp4", poster: "/portfolio/motion/wuwh.webp", blur: "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAAAwBACdASoMABUAPu1iqU2ppaOiMAgBMB2JaQAD5bndeLiArDa1DaYTeIAA/uc/XM8Echbh0qS+B6DDHhhwG/AH5pGOXwBZqX2DifIk6y2f2PVbj7U91Gi1iusamL4erBs1Mn7DQvrWd7de5/oL/5qf8JtDsbqQSj95ttPArboruzpGZAAAAA==" },
  { id: "money", series: "money", title: "Money Talkz", video: "/portfolio/motion/money.mp4", poster: "/portfolio/motion/money.webp", blur: "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAADwAwCdASoMABUAPu1iqU2ppaOiMAgBMB2JZgCdAYyAdeKqoAcQuMsAAP6mrA1TLWdcub6vL8ZUlHZNpwqSVgwqqGp16aBq+nqNF2jNRbdtFkMm7c0TvSEcSkCqr4ij50ry5GB65dHJ9gdG//b48oC8n2l2u4Wglel8Omlo8IO6i9aanFELxVeG46VZUllMC0MvgIRGWAAAAA==" },
  { id: "berlin", series: "berlin", title: "Berlin · Elex 4 Friends", video: "/portfolio/motion/berlin.mp4", poster: "/portfolio/motion/berlin.webp", blur: "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAABwBACdASoMABUAPu1iqU2ppaOiMAgBMB2JbACdMoR3ACxpGLpI+aeHUKejLAD+1xta5JeFjg/uJiFW9BMqlWxHyi88Y/FLAD6Lp+nFGBwkMLXWBvmne2zDzhO1MJbktXioCneowehBnWy5N3F6ubNi0UF8kYB3JV9XrPNnn9IQ6NkAAAA=" },
  { id: "monalisa", series: "candy", title: "Candy Night · Monalisa", video: "/portfolio/motion/monalisa.mp4", poster: "/portfolio/motion/monalisa.webp", blur: "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAABQBACdASoMABUAPu1iqU2ppaOiMAgBMB2JaACdMoRwACW441nM5Ky1mNaAAP6RdCIShXgZq7Ehh1kFH9x5WAw/N7IjSejPq6+jvCps5EcnySoyFMHmtg2t5SirfYFGUf1dUxy8AAA=" },
  { id: "urban", series: "blessed", title: "Urban Night", video: "/portfolio/motion/urban.mp4", poster: "/portfolio/motion/urban.webp", blur: "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAAAwBACdASoMABUAPu1iqU2ppaQiMAgBMB2JZACdMoAC/B6acBuEwvWDZ4AA/uwRhiPj98E22SmvlN7jtphGcFz42areUXz4qMOx8UEGiJcelPOZmSazQXN6+DwU9xp2Y4s9C0LR5C+FtA2873VXt93AjEaQf5VY1IirHPedTAAAAA==" },
  { id: "badbunny", series: "blessed", title: "Bad Bunny Night", video: "/portfolio/motion/badbunny.mp4", poster: "/portfolio/motion/badbunny.webp", blur: "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAABQBACdASoMABUAPu1iqU2ppaOiMAgBMB2JbACdMoGv/gJLMmI6T52uTpjAAP7usaiuyBNEfmkypb25j5tEcJI0u+kfJHWAUwvFHlQXc5xaHO67FitzQ9ARxQ6exE/qZZSoHQa/ZUKZw8CsxS+O2vsxauYGZMvzSzGLwFs9vV2zsNQyiRH8zU14Dz3g3M0U2P9PFzBiBAAAAA==" },
  { id: "albanien", series: "blessed", title: "Albanien Night", video: "/portfolio/motion/albanien.mp4", poster: "/portfolio/motion/albanien.webp", blur: "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAAAQBACdASoMABUAPu1iqU2ppaOiMAgBMB2JZACdAB6Vr9NTGtcfkojOwAD+7rGorsc3jGSp0+K/5R88Vqzun3QYA+YDCMMvfOMUZgbvm/UOF+I3MYYC8i8CG8Sr1gqfAKw28IrzyIhqOf8eTKR/m+owTgWVIDe82BgAAA==" },
  { id: "balkan", series: "blessed", title: "Blessed Balkan", video: "/portfolio/motion/balkan.mp4", poster: "/portfolio/motion/balkan.webp", blur: "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAACQAwCdASoMABUAPu1iqU2ppaQiMAgBMB2JbACsAB46dVJy0HGAAP7pR2T3aCvZzTpfXm8Q+4yJiAtcI+l/Ld8USHnXAmIOfzK+wQmW7lKGR4Fl+wtuJ3bZfNQVICiqwqoqOt4sESrMMV8AX11ia9XWdpmqdDiZIXpvfa2h1Dk+ptxAAAA=" },
  { id: "luvsick-green", series: "luvsick", title: "LUVSICK · 3D Shirt Green", video: "/portfolio/motion/luvsick-green.mp4", poster: "/portfolio/motion/luvsick-green.webp", blur: "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAACwAwCdASoMABUAPu1iqU2ppaOiMAgBMB2JZyzAAAGEelyS5oPeAAD+zgejrF0/CXdawsR7rf9zLyTVwdjpndY3a4OcK1pNNQTVAAAA" },
  { id: "luvsick-bw", series: "luvsick", title: "LUVSICK · 3D Shirt B&W", video: "/portfolio/motion/luvsick-bw.mp4", poster: "/portfolio/motion/luvsick-bw.webp", blur: "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACQAwCdASoMABUAPu1iqU2ppaQiMAgBMB2JaSzAAAGEehwTHKdAAP7OB6OsXT8Jd1rCxHu0QLoY2sd2y1UYKpfVpmA1wOBAAAA=" },
  { id: "luvsick-pink", series: "luvsick", title: "LUVSICK · 3D Shirt Pink", video: "/portfolio/motion/luvsick-pink.mp4", poster: "/portfolio/motion/luvsick-pink.webp", blur: "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACQAwCdASoMABUAPu1iqU2ppaOiMAgBMB2JaSzAAAGEelremoIAAP7OB6OsXT8Jd1rCxHtxfZGWJy3badkOrUkNBAAAAA==" },
  { id: "luvsick-trailer", series: "luvsick", title: "LUVSICK · Trailer", video: "/portfolio/motion/luvsick-trailer.mp4", poster: "/portfolio/motion/luvsick-trailer.webp", blur: "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAAAQBACdASoMABUAPu1kq04ppaQiMAgBMB2JbACdMoADTqHOaAeozbtRsAD9wRcYaeY5jLgWgahT3uBTUcBOpd5lkasjP3WXJXb0YdqOy9tQ34zGQh3H5Xepf9SRyGXxcxXFyV/tcaaro6sJP4YcZPa48IrbyRoJjS20FdkkyzbD202AAAA=" },
  { id: "catchme", series: "catchme", title: "Catch Me · Teaser", video: "/portfolio/motion/catchme.mp4", poster: "/portfolio/motion/catchme.webp", blur: "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAwCdASoMABUAPu1iqU2ppaOiMAgBMB2JZQCdMoADZC2EI2QviSogAP7r8docO2BlCOXx11c3sHEXfH9JudP0+doz6XP4kqY/kpZoKq6l27bBDxNzGAAA" },
  { id: "money-reel1", series: "money", title: "Money Talkz · Reel Bottle Service", video: "/portfolio/motion/money-reel1.mp4", poster: "/portfolio/motion/money-reel1.webp", blur: "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAAAQBACdASoMABUAPu1iqU2ppaOiMAgBMB2JbACdMoADfwVOHfI3P8a/AADNsWcJxo1Z7nP+YgUUyRkmcXq7Phv1ZpDOIlwUqLOq/sfjBXrrOdFGpS4FvawHZH5SOOSotJRpyW+zNrXKzJgA" },
  { id: "money-reel2", series: "money", title: "Money Talkz · Reel Dancefloor", video: "/portfolio/motion/money-reel2.mp4", poster: "/portfolio/motion/money-reel2.webp", blur: "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAABwBACdASoMABUAPu1mq04ppaQiMAgBMB2JagCdMoGv/gvBDtgPem6u7jDigAD+/knaUCLJsBX65XMNmPUi/Bcjb3IPtQUpQRnDmCoXLF7eFD+JtP1xIlh1NkD9qeMTTIn1tsyYH/Az6gQuQddowinAcIjPFqMzbrMkshoBkEy3M8oWWOy2E9++FX3HXGZqqf4H11WcG8BAAA==" },
  { id: "faqyri", series: "blessed", title: "Blessed · Faqyri Night", video: "/portfolio/motion/faqyri.mp4", poster: "/portfolio/motion/faqyri.webp", blur: "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAwCdASoMABUAPu1iqU2ppaOiMAgBMB2JZQCdACFnb0yVttx4EvqAAP7lrLhoLYwgZDVHYMzmq0HtP6a8TjGL4KaUEalI8YM7o5hyvDxMXwIAAAA=" },
  { id: "hnb-muster", series: "hnb", title: "Hot'n Brownie · Flyer Package", video: "/portfolio/motion/hnb-muster.mp4", poster: "/portfolio/motion/hnb-muster.webp", blur: "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAAAQBACdASoMABUAPu1iqU2ppaOiMAgBMB2JbACdABufTKU6VpeYgt0gUAD+5Fo2Bp5zknSEln9zNI4py7+L4SHXzfoioa68eKangiFWEhrqD6tW5ESOB1MVP+W255H2bEA4vD/SPriWcIbtDDXsv1MEI/58mES+Ot6ldl5qvQBZvAAA" },
];

/** Event- und Location-Fotos (Querformat wird im Slider zugeschnitten, die Lightbox zeigt das ganze Bild) */
export const galleryPhotos: GalleryFlyer[] = [
  { id: "mt4606", series: "money", title: "Money Talkz · La Louve", src: "/portfolio/photos/mt4606.webp", width: 1100, height: 1375, blur: "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAwAgCdASoMAA8AA4BaJQBOgCIZquNJ9Q6IAAD++ROYFYRwZu75x/uX1B1l2IZvq2l1CcBVHN+UfU0jxfXp3mlkMEK1YmYRbJ53nu8dgcRtfAB/Dp63zzKpQ7C/FHyWnLFY8fYA" },
  { id: "mt4747", series: "money", title: "Money Talkz · La Louve (2)", src: "/portfolio/photos/mt4747.webp", width: 1100, height: 1375, blur: "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAAAQAgCdASoMAA8AA4BaJZgCdAYstjKQeTgAAP7s9Z7TP8DDRPNWqW/5+dm9b8itfiEP094Ktb2ZOQ8TU2Vb5V5kDqBOpltGIO4VE8ODb8LBJ9Urpp+vSQY/Js5M6O2MRdk6SnCAAAA=" },
  { id: "mt4875", series: "money", title: "Money Talkz · La Louve (3)", src: "/portfolio/photos/mt4875.webp", width: 1100, height: 1375, blur: "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAQAgCdASoMAA8AA4BaJZgCdAYvXtk+surgAP70t5+dwhDHqavka5iUDZ6+ZcmSqrAdOJRCaLDJ7ir855/jOy1PjQvKhTfd3pgYIYYxM+5pCVKfDjK62wZs9hm2yeZer3k1YJNVONNHcLVdxreM+4AA" },
  { id: "mt4894", series: "money", title: "Money Talkz · La Louve (4)", src: "/portfolio/photos/mt4894.webp", width: 1100, height: 1375, blur: "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAQAgCdASoMAA8AA4BaJagCdAEO0Ith0VwAAP74bE8BRjMsVss6yD1YbNMPvN2ndyHPYVR4kp4ISUlD1dnGcl/QGm1n/85pUzjZ1gHq9BYwcL3rvf+jepx6RXJZpUw/jsKF6h8535MR1mEdwAA=" },
  { id: "mt4708", series: "money", title: "Money Talkz · La Louve (5)", src: "/portfolio/photos/mt4708.webp", width: 1100, height: 1375, blur: "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAAAQAgCdASoMAA8AA4BaJbACdAEUpON/qawAAP7veOTYwUEZVolDro326G0X4yeJRfSVJv+eQ98Y5mFWy83ZljAE+Bu40lY20u4x2anzb5rSZ9R1lGDuandh0pR9uJ2QemZE1tRUhAAAAA==" },
  { id: "mt4944", series: "money", title: "Money Talkz · La Louve (6)", src: "/portfolio/photos/mt4944.webp", width: 1100, height: 1375, blur: "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAABwAgCdASoMAA8AA4BaJbACdAYt9ge6ODZRlUwAAP5fM8nZPRjzUq3zcCnAH9GYwBLRSjxaiaPfx6YiHqso4pXK8hpZTGzObQW+2mncuyIaaFEeAioRKD61Nmp3iEuc50gRhpFj39qjwBVlNdQAAA==" },
  { id: "yves07", series: "yves", title: "YVES Club · Bar", src: "/portfolio/photos/yves07.webp", width: 934, height: 1400, blur: "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAAAQBACdASoMABIAPu1iqU2ppaOiMAgBMB2JbACdACBvoGhu/pZlrmNkAAD+7I9o7gSrYagMwgloyv4PrlDhzmOMgsDu/G+PCTcpXuocPfWCajPEpbCrmSp4XdeA18JpHAwtflZCha/ZVYmZsxY7Y4tiabeUuoSEGAA=" },
  { id: "yves09", series: "yves", title: "YVES Club · Lounge", src: "/portfolio/photos/yves09.webp", width: 934, height: 1400, blur: "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAwBACdASoMABIAPu1iqU2ppaOiMAgBMB2JYgC7ABul48qrzn4iQAKoAAAA/u7psUgbOJYzhxeUB4BPli0GOUYRTYImqETbPCfhDrC5PgSZj1JisxByzJCExqnBMZBAYIAAAA==" },
  { id: "yves10", series: "yves", title: "YVES Club · Lounge (2)", src: "/portfolio/photos/yves10.webp", width: 934, height: 1400, blur: "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAQBACdASoMABIAPu1iqU2ppaOiMAgBMB2JZACdACIfsu7u1xHcENhFAAD+6QEGUqCwNqmEJjpcIeu2lDY/zVkX3wIX3J1IFRryori4g0JCTrkeN/rGO/O1bMP+znP+0Vr7rHOuj9T2YK1AAAA=" },
  { id: "yves21", series: "yves", title: "YVES Club · Bear Lounge", src: "/portfolio/photos/yves21.webp", width: 1100, height: 734, blur: "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoMAAgAA4BaJbACdADdjiCTGsAA/vQzucGrhVPkeLHGx0QSNRittgCAZ1pF6shq5cyEOyXtxHePjooq+772ODoAAAA=" },
  { id: "yves22", series: "yves", title: "YVES Club · Bear Lounge (2)", src: "/portfolio/photos/yves22.webp", width: 1100, height: 734, blur: "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoMAAgAA4BaJbACdAELVc+mkAAA/vEC257rvuGYGTmMJDmM/raFhpfxCJQSgT9D2LTwAO4ITY2cNu0szdVxH/novy8AAA==" },
];
