import {
  Archive,
  AudioLines,
  Award,
  Building2,
  CalendarCheck,
  Camera,
  Captions,
  Car,
  ChartLine,
  ChefHat,
  Clapperboard,
  CodeXml,
  CreditCard,
  FileText,
  Frame,
  Handshake,
  Headphones,
  Languages,
  Layers,
  Lock,
  MapPin,
  Medal,
  MessageSquareText,
  Monitor,
  Phone,
  Plug,
  RefreshCw,
  Rocket,
  Scale,
  Scissors,
  Search,
  ShieldCheck,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Split,
  Star,
  Target,
  Users,
  Utensils,
  Workflow,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

/** Icon-IDs aus den Content-Configs → Lucide (ein Icon-Set, 1.75px Strich, keine Emojis) */
export const ICONS: Record<string, LucideIcon> = {
  archive: Archive,
  audio: AudioLines,
  award: Award,
  building: Building2,
  calendar: CalendarCheck,
  camera: Camera,
  captions: Captions,
  car: Car,
  card: CreditCard,
  cart: ShoppingCart,
  chart: ChartLine,
  chef: ChefHat,
  clapperboard: Clapperboard,
  code: CodeXml,
  file: FileText,
  frame: Frame,
  handshake: Handshake,
  headphones: Headphones,
  languages: Languages,
  layers: Layers,
  lock: Lock,
  map: MapPin,
  medal: Medal,
  message: MessageSquareText,
  monitor: Monitor,
  phone: Phone,
  plug: Plug,
  refresh: RefreshCw,
  rocket: Rocket,
  scale: Scale,
  scissors: Scissors,
  search: Search,
  shield: ShieldCheck,
  smartphone: Smartphone,
  sparkles: Sparkles,
  split: Split,
  star: Star,
  target: Target,
  users: Users,
  utensils: Utensils,
  workflow: Workflow,
  wrench: Wrench,
  zap: Zap,
};

export function Icon({ name, className }: { name: string; className?: string }) {
  const C = ICONS[name] ?? Sparkles;
  return <C className={className} strokeWidth={1.75} aria-hidden />;
}
